### PR TITLE
Remove Travis CI

### PR DESCRIPTION
**Pull request by chrisburr**

### CODE REVIEW

**Comment by henryiii** [comment]
@eduardo-rodrigues did you enable pre-commit.ci? Someone did. It needs a pre-commit file to be enabled.

**Comment by eduardo-rodrigues** [comment]
I did not. (I can't act too much today due to annual meeting at Liverpool the whole day.)

**Comment by henryiii** [comment]
I turned it off. It's possible I turned it on accidentally (I didn't know it "fails" without a pre-commit config when I first set things up).

**Comment by henryiii** [comment]
Actually, with it off, it won't rerun when we close and open, so we can just merge.

**Comment by eduardo-rodrigues** [comment]
> I turned it off. It's possible I turned it on accidentally (I didn't know it "fails" without a pre-commit config when I first set things up).

So this explains what I saw with the most recent updates to DecayLanguage ... and it then obliged me to get pre-commit and formatting there - positive overall :D.

**Pull request merged**
