### PR TITLE
github actions

### PR DESCRIPTION
**Pull request by mayou36**

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
Let me ping @henryiii - we should ensure we modernise all CIs. This should probably be merged before https://github.com/scikit-hep/formulate/pull/27.

**Comment by eduardo-rodrigues** [comment]
I think Travis is dragging and we can ignore it. To be removed, actually.

Maybe @chrisburr has comment as well, as package author?

**Comment by mayou36** [comment]
yep, agree

**Comment by eduardo-rodrigues** [comment]
Morning @mayou36. I would suggest that you merge this by the end of the day unless there's feedback. Having the actions running is far better than not ;-). I believe you're not totally following the examples/guidelines in scikit-hep.org but that can be adjusted later if you prefer. As said, at least we get a running CI again.

**Comment by mayou36** [comment]
Agree! Yep, it was an ad-hoc thing, I'll give it an updat
and then I'll merge

**Comment by henryiii** [comment]
Agree, we need to remove Travis from all of our packages - it will be turned off for OSS on Dec 31.

**Comment by henryiii** [comment]
I would avoid "Python Package" unless it's actually making Python packages; "CI" or something like that should be used for tests. (It shows up in the badge).

**Pull request merged**
